aeraki-mesh/aeraki

.ci/yamllint.yml
.github/mergify.yml
.github/workflows/ci.yaml
.gitignore

enable github ci

---

.github/workflows/ci.yaml
dubbo/generator/generator.go
pkg/mcp/server.go
test/testservice.yaml

fix golang lint

---

.github/workflows/ci.yaml

add timeout to golang lint

---

pkg/bootstrap/server.go
pkg/config/configcontroller.go
pkg/mcp/server.go

Organize log information

---

pkg/envoyfilter/generator.go
pkg/mcp/server.go
pkg/model/config.go
plugin/dubbo/generator/dubboproxy.go
plugin/dubbo/generator/generator.go

We can't assume interface name is identical to host name because interface name can have capital letters

use serviceentry annotation to pass in dubbo service interface

---

go.mod
go.sum

replace istio package due to adsc issue
https://github.com/istio/istio/pull/29296

fix adsc issue

---

pkg/config/configcontroller.go
test/virtualservice-traffic-splitting.yaml
test/virtualservice-v1.yaml
test/virtualservice-v2.yaml

Add test file

---

README.md
configdump
plugin/thrift/route.go
test/dubbo/destinationrule.yaml
test/dubbo/dubbo-sample.yaml
test/thrift/destinationrule.yaml
test/thrift/thrift-sample.yaml

add demo video link

---

pkg/envoyfilter/replcae_network_filter.go
plugin/dubbo/generator.go
plugin/thrift/generator.go

refactor: extract common method

---

.github/workflows/ci.yaml

add go lint to git workflow

---

.github/workflows/ci.yaml

remove shell check

---

test/e2e/dubbo/dubbo_test.go
test/e2e/thrift/thrift_test.go

Add Thrift e2e test

---

.github/workflows/e2e.yaml

Allow pr to access github secret

---

plugin/dubbo/route.go
test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/virtualservice-route-by-method.yaml

Use the method field in http to represent the calling method in dubbo.

[ADD]add route config for dubbo method

---

test/e2e/dubbo/dubbo_test.go
test/e2e/thrift/thrift_test.go

keep the output of e2e testing tidy

---

test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/dubbo-sample.yaml
test/e2e/thrift/testdata/thrift-sample.yaml
test/e2e/thrift/thrift_test.go

Refactor testing

---

config
plugin/thrift/generator.go
plugin/thrift/route.go
plugin/thrift/thriftproxy.go
test/e2e/thrift/thrift_test.go

Support thrift at the inbound listener

---

test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/virtualservice-traffic-splitting.yaml
test/e2e/thrift/testdata/virtualservice-traffic-splitting.yaml
test/e2e/thrift/thrift_test.go

Add more samples to make percentage routing test more stable.

fix percentage routing test

---

demo/dubbo/install.sh
demo/dubbo/uninstall.sh
demo/install-demo.sh
demo/kafka/uninstall.sh
demo/thrift/install.sh
demo/thrift/uninstall.sh
demo/uninstall-demo.sh

update demo scripts

---

pkg/envoyfilter/generator.go
pkg/envoyfilter/network_filter.go
pkg/mcp/server.go
pkg/model/config.go
plugin/dubbo/generator.go
plugin/kafka/generator.go
plugin/thrift/generator.go
plugin/zookeeper/generator.go

Use labelselector to avoid ports conflict at the inbound listeners
https://github.com/aeraki-framework/aeraki/issues/49

fix inbound port conflicts

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-kafka-zookeeper.yaml
.github/workflows/e2e-thrift.yaml
Makefile
test/e2e/common/aeraki.yaml

fix workflow security issue

---

cmd/aeraki/main.go
docker/Dockerfile
k8s/aeraki.yaml
pkg/bootstrap/server.go
pkg/config/controller.go
pkg/kube/controller/controller.go
pkg/model/config.go
test/e2e/redis/redis_test.go
test/e2e/thrift/thrift_test.go

Support TCM managed mesh

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-kafka-zookeeper.yaml
.github/workflows/e2e-redis.yaml
.github/workflows/e2e-thrift.yaml
cmd/aeraki/main.go
demo/dubbo/dubbo-sample.yaml
demo/install-demo.sh
docker/Dockerfile
go.sum
k8s/aeraki.yaml
pkg/bootstrap/options.go
pkg/bootstrap/server.go
pkg/config/serviceentry/controller.go
pkg/envoyfilter/controller.go
pkg/model/utils.go
plugin/dubbo/route.go
test/e2e/common/istio-config.yaml
test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/dubbo-sample.yaml
test/e2e/scripts/aeraki.sh

enable multiple dubbo interfaces at an appliction

---

.github/workflows/e2e-dubbo.yaml
test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/serviceentry.yaml

add test for multiple interfaces in a process

---

api/dubbo/v1alpha1/authorization_policy.proto

add proto type for dubbo authorization rule

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-kafka-zookeeper.yaml
.github/workflows/e2e-redis.yaml
.github/workflows/e2e-thrift.yaml
demo/dubbo/dubbo-sample.yaml
test/e2e/common/istio-config.yaml

upgrade istio to 1.10.0

---

README.md
plugin/dubbo/route.go
test/e2e/dubbo/dubbo_test.go
test/e2e/dubbo/testdata/destinationrule.yaml
test/e2e/dubbo/testdata/dubbo-sample.yaml
test/e2e/dubbo/testdata/virtualservice-header-exact.yaml
test/e2e/dubbo/testdata/virtualservice-method-exact.yaml
test/e2e/dubbo/testdata/virtualservice-method-prefix.yaml
test/e2e/dubbo/testdata/virtualservice-traffic-splitting.yaml
test/e2e/dubbo/testdata/virtualservice-v1.yaml
test/e2e/dubbo/testdata/virtualservice-v2.yaml

support header based routing

---

go.mod
go.sum
pkg/envoyfilter/controller.go

use debounce lib

---

api/metaprotocol/v1alpha1/metaprotocol_metarouter.proto
demo/metaprotocol-dubbo/metarouter-v1.yaml
demo/metaprotocol-dubbo/metarouter-v2.yaml
docs/metaprotocol.md
pkg/xds/cache_mgr.go
test/e2e/metaprotocol/metaprotocol_test.go
test/e2e/metaprotocol/testdata/metarouter-attribute-exact.yaml
test/e2e/metaprotocol/testdata/metarouter-attribute-prefix.yaml
test/e2e/metaprotocol/testdata/metarouter-attribute-regex.yaml
test/e2e/metaprotocol/testdata/metarouter-attribute-splitting.yaml
test/e2e/metaprotocol/testdata/metarouter-v1.yaml

fix: attribute match doesn't work

---

demo/thrift/uninstall.sh

thrift demo uninstall.sh not work

fix thrift demo uninstall.sh

---

Makefile
README.md

+ add tag to build image
+ add test to lazyxds

chore(aeraki,lazyxds): add tag to build image and add test to lazyxds

---

.github/mergify.yml

notify reviewers only when PR is not a draft

optimize: notify reviewers only when PR is not a draft

---

README.md

fix: correct wrong name of aeraki

fix: correct wrong name of aeraki

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add PR template to aeraki

chore: add PR template to aeraki

---

README.md

optimize: align logo to readme center

---

.github/workflows/ci.yaml
.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-kafka-zookeeper.yaml
.github/workflows/e2e-lazyxds.yaml
.github/workflows/e2e-metaprotocol.yaml
.github/workflows/e2e-redis.yaml
.github/workflows/e2e-thrift.yaml
README.md
docs/metaprotocol.md
lazyxds/README.md

optimize: speed up ci to merge

optimize: speed up ci to merge

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-kafka-zookeeper.yaml
.github/workflows/e2e-lazyxds.yaml
.github/workflows/e2e-metaprotocol.yaml
.github/workflows/e2e-redis.yaml
.github/workflows/e2e-thrift.yaml

fix: remove ignore pass to avoid mismatch of expected actions

fix: remove ignore paths to avoid mismatch of expected actions

---

docs/metaprotocol.md

fix: correct metarouter field

---

Makefile
README.md

[WIP] chore: provide commands to run aeraki

chore:  provide commands to run aeraki

---

README.md

chore: add license badge to list

chore: add license badge to list

---

CODE_OF_CONDUCT.md

add code of conduct to aeraki community

chore: add code_of_conduct to aeraki community

---

demo/metaprotocol-videopacket/destinationrule.yaml
demo/metaprotocol-videopacket/install.sh
demo/metaprotocol-videopacket/metarouter-v1.yaml
demo/metaprotocol-videopacket/metarouter-v2.yaml
demo/metaprotocol-videopacket/traffic-split.yaml
demo/metaprotocol-videopacket/uninstall.sh
demo/metaprotocol-videopacket/videopacket-protocol.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml

add test app for videopacket

---

pkg/xds/cache_mgr.go

fix: regex match condtion

---

demo/metaprotocol-qza/destinationrule.yaml
demo/metaprotocol-qza/install.sh
demo/metaprotocol-qza/metarouter-v1.yaml
demo/metaprotocol-qza/metarouter-v2.yaml
demo/metaprotocol-qza/qza-protocol.yaml
demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-qza/traffic-split.yaml
demo/metaprotocol-qza/uninstall.sh
pkg/xds/cache_mgr.go

Qza example

---

demo/metaprotocol-qza/destinationrule.yaml
demo/metaprotocol-qza/install.sh
demo/metaprotocol-qza/metarouter-v1.yaml
demo/metaprotocol-qza/metarouter-v2.yaml
demo/metaprotocol-qza/qza-protocol.yaml
demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-qza/traffic-split.yaml
demo/metaprotocol-qza/uninstall.sh
demo/metaprotocol-trpc/destinationrule.yaml
demo/metaprotocol-trpc/install.sh
demo/metaprotocol-trpc/metarouter-v1.yaml
demo/metaprotocol-trpc/metarouter-v2.yaml
demo/metaprotocol-trpc/traffic-split.yaml
demo/metaprotocol-trpc/trpc-protocol.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-trpc/uninstall.sh
pkg/xds/cache_mgr.go

Trpc example

---

demo/metaprotocol-thrift/thrift-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
pkg/envoyfilter/network_filter.go
pkg/envoyfilter/network_filter_test.go

Related Aeraki issue: https://github.com/aeraki-framework/aeraki/issues/149
PS: Currently, Istio only assign one vip to the address list of a
service entry. To fix this issue, the Istio issue needs to be fixed as
well: https://github.com/istio/istio/issues/36694

Create outbound listener on every vip

---

cmd/aeraki/main.go
docker/Dockerfile
go.mod
k8s/aeraki.yaml
pkg/bootstrap/options.go
pkg/bootstrap/server.go
pkg/envoyfilter/controller.go
pkg/kube/controller/controller.go
pkg/leaderelection/leaderelection.go
pkg/leaderelection/leaderelection_test.go

* EnvoyFilter controller and VIP allocation controller supports HA
with leader election
MetaProtcol RDS server supports Horizontal scaling for large scale
deployment

Support high availability and horizontal scaling

---

.github/mergify.yml
Makefile
README.md
demo/install-aeraki.sh
pkg/config/controller.go
test/e2e/kafka/kafka_zookeeper_test.go
test/e2e/scripts/aeraki.sh
test/e2e/scripts/istio.sh

finalize 1.0.0

---

.github/mergify.yml

via: https://github.com/aeraki-mesh/aeraki/pull/156/checks?check_run_id=4787204867

ci: fix merge action to keep linear history

---

README.md

docs: add slack channel in istio

---

pkg/config/controller.go
pkg/xds/utils.go

https://github.com/aeraki-mesh/aeraki/pull/160

Fix: rds is wrong when there're multiple match conditions

---

pkg/envoyfilter/network_filter.go
pkg/xds/cache_mgr.go
plugin/dubbo/generator.go
plugin/metaprotocol/generator.go
plugin/metaprotocol/metaprotocolproxy.go
plugin/metaprotocol/route.go
plugin/redis/generator.go
plugin/thrift/generator.go

support multiple MetaProtocol ports in a service #164

support multiple MetaProtocol ports in a service #164

---

demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml

rename proxy image

---

pkg/config/controller.go

Related istio issue: https://github.com/istio/istio/issues/36694
Related istio pr: https://github.com/istio/istio/pull/36820

fix #149 support multi VIPs

---

Makefile
cmd/aeraki/main.go
demo/install-aeraki.sh
demo/install-demo.sh
docker/Dockerfile
go.sum
k8s/aeraki.yaml
k8s/tcm-apiservice.yaml
pkg/bootstrap/options.go
pkg/bootstrap/server.go
pkg/config/controller.go
test/e2e/scripts/aeraki.sh

#168 Support TLS connection to Istiod
#169 Support deploying Aeraki to TCM managed service mesh

support tls connection to istiod and deploying in TCM

---

cmd/aeraki/main.go
docker/Dockerfile
k8s/aeraki.yaml
pkg/bootstrap/options.go
pkg/bootstrap/server.go
test/e2e/scripts/aeraki.sh

Related issue: #174 We need multicluster support

support multi cluster

---

demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml

Related issue:https://github.com/aeraki-mesh/aeraki/issues/180

add test file for outlier detection

---

go.mod
go.sum

Related issue: https://github.com/aeraki-mesh/aeraki/issues/183

support consistent hash LB

---

go.mod
go.sum
pkg/config/controller.go
pkg/model/config.go
pkg/xds/cache_mgr.go
pkg/xds/utils.go

Session affinity

---

demo/metaprotocol-dubbo/consistent-hash-lb/destinationrule.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-qza/destinationrule.yaml
demo/metaprotocol-thrift/consistent-hash-lb/destinationrule.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
demo/metaprotocol-trpc/destinationrule.yaml
demo/metaprotocol-videopacket/destinationrule.yaml
demo/thrift/destinationrule.yaml
pkg/bootstrap/server.go
pkg/config/controller.go
pkg/envoyfilter/controller.go
pkg/model/protocol/instance.go
pkg/model/protocol/instance_test.go
pkg/model/utils.go
pkg/xds/cache_mgr.go
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml

Support short service name

---

.github/workflows/ci.yaml
demo/install-demo.sh
demo/metaprotocol-trpc/metarouter-v1.yaml
demo/metaprotocol-trpc/metarouter-v2.yaml
demo/metaprotocol-trpc/trpc-sample.yaml

https://github.com/aeraki-mesh/meta-protocol-proxy/issues/43

support streaming rpc

---

demo/dubbo/virtualservice-traffic-splitting.yaml
demo/kafka/install.sh

fix: https://github.com/aeraki-mesh/aeraki/issues/188

fix helm repo

---

README.md

Add Aeraki Mesh Info in Landscape

---

README.md

Fixed some typos in *README.md*.

Fix some typo

---

README_CN.md

Signed-off-by: Wen-Quan Li [legendarilylwq@gmail.com](mailto:legendarilylwq@gmail.com)
fix #198 : Add a Chinese version of README

Add Chinese README

---

demo/metaprotocol-trpc/metarouter-multi-route.yaml
demo/metaprotocol-trpc/trpc-sample.yaml

1.Add metarouter-multi-route.yaml to configure multi-version routing configuration
2.Modify the client deployment yaml and increase the version environment variable

Add multi-version routing test configuration:

---

.gitignore
Makefile
demo/install-demo.sh
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-brpc/destinationrule.yaml
demo/metaprotocol-brpc/install.sh
demo/metaprotocol-brpc/service.yaml
demo/metaprotocol-brpc/serviceentry.yaml
demo/metaprotocol-brpc/traffic-split.yaml
demo/metaprotocol-brpc/uninstall.sh
demo/uninstall-demo.sh

add brpc demo

---

Makefile
go.mod
go.sum
pkg/xds/cache_mgr.go
pkg/xds/utils.go

feat: traffic mirroing control plane impl

---

demo/install-demo.sh
demo/uninstall-demo.sh

fix: demo install script reports error #224

---

demo/metaprotocol-brpc/brpc-protocol.yaml
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml

https://github.com/aeraki-mesh/aeraki/issues/222

chore: update metaprotocol proxy to 1.1.0

---

pkg/envoyfilter/network_filter.go
pkg/envoyfilter/network_filter_test.go

fix for https://github.com/aeraki-mesh/aeraki/issues/247

fix for workload selector by dubbo2istio

---

test/e2e/metaprotocol/metaprotocol_test.go
test/e2e/metaprotocol/testdata/consistent-hash-lb/destinationrule.yaml
test/e2e/metaprotocol/testdata/consistent-hash-lb/metarouter-sample.yaml

Add consistent hash load balancing e2e testing for pr #235

Add consistent hash load balancing e2e testing

---

demo/install-demo.sh

update prometheus and grafana to release 1.12

---

test/e2e/metaprotocol/metaprotocol_test.go
test/e2e/metaprotocol/testdata/rate-limit-server/config.yaml

Signed-off-by: Sad-polar-bear <942583449@qq.com>

fix rate limit test

---

.licenserc.yaml

fix: add .md to pass ci failed

---

MAINTAINERS.md

Fix a typo in maintainer.md

---

.golangci.yml
demo/common_func.sh
pkg/bootstrap/server.go
pkg/ca/certificate.go
pkg/controller/istio/controller.go
pkg/controller/kube/dubbo.go
pkg/controller/kube/metaprotocol.go
pkg/envoyfilter/controller.go
pkg/envoyfilter/network_filter.go
pkg/webhook/validation/scheme/validation.go
pkg/xds/cache_mgr.go
pkg/xds/callbacks.go
pkg/xds/utils.go
plugin/dubbo/dubboproxy.go
plugin/dubbo/route.go
plugin/metaprotocol/filters.go
plugin/metaprotocol/metaprotocolproxy.go
plugin/metaprotocol/route.go
plugin/redis/generator.go
plugin/redis/util.go
test/e2e/util/kube_utils.go
test/e2e/util/retry.go

fix code format check

---

.github/workflows/e2e-metaprotocol.yaml
demo/install-demo.sh
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-dubbo/traffic-mirroring.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
pkg/bootstrap/webhook.go
pkg/webhook/validation/scheme/validation.go
pkg/xds/cache_mgr.go
test/e2e/metaprotocol/metaprotocol_test.go
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml
test/e2e/metaprotocol/testdata/traffic-mirroring.yaml

* Add e2e test for traffic mirroring
* Fix some mirror percent issues
https://github.com/aeraki-mesh/aeraki/issues/200

finish up traffic mirroring

---

.github/workflows/e2e-metaprotocol.yaml
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-dubbo/metarouter-header-mutation.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
test/e2e/metaprotocol/metaprotocol_test.go
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml
test/e2e/metaprotocol/testdata/metarouter-header-mutation.yaml
test/e2e/util/kube_utils.go

https://github.com/aeraki-mesh/meta-protocol-proxy/issues/54

dubbo header mutation

---

pkg/envoyfilter/network_filter.go

Signed-off-by: panniyuyu@gmail.com <panniyuyu@gmail.com>

fix: empty ServiceEntry WorkloadSelector cause panic

---

README.md
README.zh-CN.md

Signed-off-by: mark <leis17@163.com>

fix docs  Signed-off-by: mark <leis17@163.com>

---

cmd/aeraki/main.go
k8s/aeraki.yaml
pkg/bootstrap/options.go
pkg/bootstrap/server.go
pkg/controller/istio/controller.go

Signed-off-by: panniyuyu@gmail.com <panniyuyu@gmail.com>

fix issue #266

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-metaprotocol.yaml
.github/workflows/e2e-redis.yaml
.github/workflows/e2e-thrift.yaml
demo/install-demo.sh
test/e2e/common/istio-config.yaml
test/e2e/scripts/istio.sh

update istio to 1.14.5

---

k8s/aeraki.yaml

add request limit

---

pkg/bootstrap/server.go

expose pprof debug port

---

demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-trpc/metarouter-header-mutation.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
pkg/model/utils.go

Support trpc header muation

---

demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml

trpc distributed tracing

---

demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
go.mod
go.sum
pkg/xds/cache_mgr.go
pkg/xds/utils.go
plugin/metaprotocol/accesslog.go
plugin/metaprotocol/filters.go
plugin/metaprotocol/metaprotocolproxy.go
plugin/metaprotocol/route.go
test/e2e/common/istio-config.yaml

access log

---

demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
plugin/metaprotocol/metaprotocolproxy.go

fix https://github.com/aeraki-mesh/aeraki/issues/295

Fix access log path

---

.github/workflows/e2e-dubbo.yaml
.github/workflows/e2e-metaprotocol.yaml
demo/install-demo.sh
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
go.mod
go.sum
plugin/metaprotocol/filters.go
plugin/metaprotocol/metaprotocolproxy.go
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml

Generate Istio metrics.
This pr is part of https://github.com/aeraki-mesh/aeraki/issues/196

Support istio style stats

---

api/metaprotocol/v1alpha1/metaprotocol_metarouter.proto
k8s/crd.yaml

Add gateways filed in crd and proto filed

Add gateways filed in crd and proto filed

---

common-protos/k8s.io/api/core/v1/generated.proto

Update k8s registry references

---

Makefile
demo/install-demo.sh
demo/uninstall-aeraki.sh
demo/uninstall-demo.sh

add uninstall aeraki script Signed-off-by: mark  leis17@163.com

---

.github/workflows/publish.yaml
Makefile
demo/dubbo/dubbo-sample.yaml
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo-app-level/dubbo-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-qza/qza-sample.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
demo/metaprotocol-trpc/trpc-sample.yaml
demo/metaprotocol-videopacket/videopacket-sample.yaml
demo/thrift/thrift-sample.yaml
k8s/aeraki.yaml
manifests/charts/aeraki/values.yaml
test/e2e/dubbo/testdata/dubbo-sample.yaml
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml
test/e2e/thrift/testdata/thrift-sample.yaml

Switch to github image since docker hub doesn't provide free access to organization

switch to github image hub

---

cmd/aeraki/main.go

update annotation Signed-off-by: mark  leis17@163.com

---

Makefile
build_api.sh
demo/dubbo/install.sh
demo/dubbo/uninstall.sh
demo/install-aeraki.sh
demo/kafka/install.sh
demo/kafka/uninstall.sh
demo/metaprotocol-brpc/install.sh
demo/metaprotocol-brpc/uninstall.sh
demo/metaprotocol-dubbo-app-level/install.sh
demo/metaprotocol-dubbo-app-level/uninstall.sh
demo/metaprotocol-dubbo/install.sh
demo/metaprotocol-dubbo/uninstall.sh
demo/metaprotocol-qza/install.sh
demo/metaprotocol-qza/uninstall.sh
demo/metaprotocol-thrift/install.sh
demo/metaprotocol-thrift/uninstall.sh
demo/metaprotocol-trpc/install.sh
demo/metaprotocol-trpc/uninstall.sh
demo/metaprotocol-videopacket/install.sh
demo/metaprotocol-videopacket/uninstall.sh
demo/thrift/install.sh
demo/thrift/uninstall.sh
demo/uninstall-aeraki.sh
demo/uninstall-demo.sh
test/e2e/scripts/istio.sh
test/e2e/scripts/uninstall-istio.sh

optimize code for aeraki

---

Makefile
docker/Dockerfile
hack/make-rules/cross_build_images.sh

support multi-arch images

---

Makefile
README.md

Aeraki support for multi-architecture image

---

demo/install-demo.sh

fix https://github.com/aeraki-mesh/aeraki/issues/343

---

test/e2e/util/common_utils.go

replace io/ioutil to os/io in golang 1.19

---

GOVERNANCE.md

Add Steering Committee definition to project governance.

add Steering Committee definition to project governace

---

GOVERNANCE.md

Dear aeraki Committee ,
I am writing to express my interest in becoming a member of the Technical Guidance Committee.
1. About myself: My name is huangli, and I have been working as a software engineer  with expertise in [alauda,huawei,fiberhome]. Throughout my career, I have gained extensive experience in designing and developing istio，envoy，k8s, cni as well as providing technical guidance and mentorship to other engineers.
2. About Alauda: it is a technology company that specializes in providing cloud-native solutions for container management and application deployment. Founded in 2014, Alauda has established itself as a leading provider of enterprise-grade Kubernetes-based platforms. 
3. About How to help aeraki: We used aeraki in Alauda service mesh to help our customers resolve …

Governance:request to join steering committee - alauda.io

---

CODE_OF_CONDUCT.md

fix https://github.com/aeraki-mesh/aeraki/issues/378

Remove mediator with CNCF Code of Conduct Committee

---

.github/workflows/e2e-metaprotocol-gateway.yaml
.github/workflows/e2e-metaprotocol.yaml
.github/workflows/e2e-redis.yaml
demo/metaprotocol-brpc/brpc-sample.yaml
demo/metaprotocol-dubbo-app-level/dubbo-sample.yaml
demo/metaprotocol-dubbo/dubbo-sample.yaml
demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml
demo/metaprotocol-thrift/thrift-sample.yaml
docs/zh/README.md
test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml
test/e2e/metaprotocolgateway/testdata/ingress-gateway.yaml
test/e2e/scripts/istio.sh
test/e2e/scripts/uninstall-istio.sh

Related issue: https://github.com/aeraki-mesh/aeraki/issues/365

Upgrade Istio to 1.18.2

---

GOVERNANCE.md

Dear Aeraki Committee,
I am writing to express my interest in becoming a member of the Technical Guidance Committee.
1. About myself: My name is Heng Luo, and I have been working as a software engineer with expertise in [Tencent]. Throughout my career, I have gained extensive experience in designing and developing Istio, Envoy, K8s as well as providing technical guidance and mentorship to other engineers.
2. About Tencent: Tencent is a leading global technology company that specializes in providing a wide range of internet services and products, including social platforms, gaming, digital content, and cloud-based solutions.
3. How to help Aeraki: We have utilized Aeraki in our service mesh to manage our proprietary protocols within Tencent's infrastructure. Leveraging our experience with …

Governance:request to join steering committee - tencent

---

cmd/aeraki/main.go
docker/Dockerfile
go.mod
k8s/aeraki.yaml

Can help users to write logs to specified log file

add startup parameters to config log

---

internal/bootstrap/server.go
internal/controller/kube/sidecar_bootstrap_config.go
internal/xds/server.go
k8s/aeraki-bootstrap-config.yaml

aeraki and envoy should communicate through mTLS for security reasons

aeraki and envoy communicate through mTLS

---

internal/controller/istio/controller.go

issue ：https://github.com/aeraki-mesh/aeraki/issues/389

fix fail to dail to xds istiod.istio-system.svc:15012

---

manifests/charts/aeraki/templates/deployment.yaml

There are a few whitespaces in the `manifests/charts/aeraki/deployment.yaml` helm chart that breaks the rendering process.

fix: Remove errant whitespace from deployment.yaml

---

manifests/charts/aeraki/templates/deployment.yaml

An errant whitespace was introduced in a previous PR which stops the template from rendering correctly

fix: Errant space in deployment.yaml

---

README.md

Update README.md fix uil
