.github/workflows/e2e.yaml
This event runs in the context of the base of the pull request, rather than in the merge commit as the pull_request event does.  So we should specify the ref and repository of the PR in the checkout action.
=> Check out codes at pull request head

.github/workflows/e2e-dubbo.yaml
percentage traffic splitting test is not accurate and causing e2e test
failing
=> remove dubbo percentage traffic splitting test

pkg/envoyfilter/network_filter.go, pkg/envoyfilter/network_filter_test.go, plugin/dubbo/generator.go, plugin/kafka/generator.go, plugin/redis/generator.go, plugin/thrift/generator.go, plugin/zookeeper/generator.go, test/e2e/dubbo/dubbo_test.go
workloadselector should be set for inbound envoy filters to avoid
override inbound config of other services at the same port
=> set workloadselector for inbound envoy filter

lazyxds/pkg/model/service.go, test/e2e/lazyxds/data/source/external-name-svc.yaml, test/e2e/lazyxds/lazyxds/lazyxds_test.go
fix issue https://github.com/aeraki-framework/aeraki/issues/83
disable lazy loading for ExternalName service and selector-less service.
=>  disable lazyxds for service without selector

demo/metaprotocol-dubbo/metarouter-v1.yaml
in demo/metaprotocol-dubbo. There's mistake about bad yaml format in "metarouter-v1.yaml" cause traffic management fail.
=> bugfix: Bad yaml format cause traffic management fail.

.github/workflows/publish.yaml, demo/thrift/uninstall.sh, plugin/redis/generator.go
feat: Support auto build and push docker image when releasing.
This ci only will be triggered by creating tags.
When creating tags like these format, this workflow will start to work:
+ ` aeraki/{version}`
+ ` lazyxds/{version}`
For example, if we create a tag named `aeraki/v0.1.1`, ci will auto build and publish a image called `aeraki/aeraki:v0.1.1` to hub.
And if we create a tag named `lazyxds/v0.1.2`, ci will auto build and publish a image called `aeraki/lazyxds:v0.1.2` to hub.
> + We need to set two secrets in GitHub Secrets: `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
> + This PR will work fine after merging this #117 PR
=> ci(aeraki,lazyxds): support auto build and push docker image

go.mod, lazyxds/pkg/controller/aggregation.go, lazyxds/pkg/controller/discovery_selector.go, lazyxds/pkg/controller/discoveryselector/controller.go, lazyxds/pkg/controller/namespace.go, lazyxds/pkg/controller/namespace/controller.go, lazyxds/pkg/controller/service.go, lazyxds/pkg/controller/service/controller.go, lazyxds/pkg/manager/manager.go, lazyxds/pkg/model/namespace.go, lazyxds/pkg/model/service.go
1. Ignore the services in those namespaces which do not match the istio discovery selector, so that these services won't be configured in the envoyFilter of lazy service.
2. Watch the changes of discovery selector, refresh all the lazy service's crds created by lazyxds before.
=> support discovery selector

demo/metaprotocol-dubbo/dubbo-sample.yaml, demo/metaprotocol-qza/destinationrule.yaml, demo/metaprotocol-thrift/consistent-hash-lb/destinationrule.yaml, demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml, demo/metaprotocol-thrift/thrift-sample.yaml, demo/metaprotocol-trpc/destinationrule.yaml, demo/metaprotocol-videopacket/destinationrule.yaml, demo/thrift/destinationrule.yaml, test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml
=> publish 1.0.4

README.md, README.zh-CN.md
fix https://github.com/aeraki-mesh/aeraki/issues/198 : Add a Chinese version of README
Add link to jump to Chinese version
=> ADD Chinese version of README

README.md, README.zh-CN.md
Signed-off-by: Sad-polar-bear <942583449@qq.com>
=> fix misspelling and improve README

demo/common_func.sh, demo/dubbo/install.sh, demo/kafka/install.sh, demo/metaprotocol-dubbo/install.sh, demo/metaprotocol-qza/install.sh, demo/metaprotocol-thrift/install.sh, demo/metaprotocol-trpc/install.sh, demo/metaprotocol-videopacket/install.sh, demo/thrift/install.sh
fix for https://github.com/aeraki-mesh/aeraki/issues/212
i want to support istio revision install when i installed demo
=> for demo install support  if istio use revision install

pkg/xds/cache_mgr.go
=> fix: mirror validation

pkg/model/utils.go, pkg/xds/cache_mgr.go, pkg/xds/utils.go
I found that consistent hash lb must set in dr.spec.trafficPolicy. I think we should align with istio. Consistent hash load balancing settings prioritizes dependent subsets.
=> Consistent hash load balancing settings prioritizes dependent subsets.

api/metaprotocol/v1alpha1/metaprotocol.aeraki.io.v1alpha1.pb.html, api/metaprotocol/v1alpha1/metaprotocol_metarouter.pb.go, api/metaprotocol/v1alpha1/metaprotocol_metarouter.proto, pkg/webhook/validation/scheme/validation.go
=> feat: add validation for global rate limit and local rate limit

demo/install-aeraki.sh
See #244 
After fixed, the output is as below
```shell
$ aeraki git:(master) ✗ make install
bash demo/install-aeraki.sh
+ '[' -z latest ']'
+ '[' -z '' ']'
+ export AERAKI_ISTIOD_ADDR=istiod.istio-system:15010
+ AERAKI_ISTIOD_ADDR=istiod.istio-system:15010
+ '[' -z '' ']'
+ export AERAKI_NAMESPACE=istio-system
+ AERAKI_NAMESPACE=istio-system
+ '[' -z '' ']'
+ export AERAKI_IS_MASTER=true
+ AERAKI_IS_MASTER=true
+ '[' -z '' ']'
+ export AERAKI_ENABLE_ENVOY_FILTER_NS_SCOPE=false
+ AERAKI_ENABLE_ENVOY_FILTER_NS_SCOPE=false
+ mkdir -p /****/****/.aeraki
+ envsubst
+ '[' '' == mode=tcm ']'
+ kubectl delete crd applicationprotocols.metaprotocol.aeraki.io
customresourcedefinition.apiextensions.k8s.io "applicationprotocols.metaprotocol.aeraki.io" deleted
+ kubectl apply -f …
```
=> fix: Fix the bug on shell script

demo/metaprotocol-brpc/install.sh, demo/metaprotocol-brpc/uninstall.sh
=> update brpc demo scripts

.golangci.yml, pkg/envoyfilter/controller.go, pkg/xds/cache_mgr.go
=> fix: golangci complexity

pkg/controller/istio/controller.go
Signed-off-by: panniyuyu@gmail.com <panniyuyu@gmail.com>
I think aeraki should not validate the service from istiod. The service that aeraki cares about has been verified by istiod when ServiceEntry is created. And there will be a lot of warning logs in console if validate the service. It's not helpful for us to troubleshoot.
=>  mcp client should not validate the service

pkg/bootstrap/server.go, pkg/model/utils.go
https://github.com/aeraki-mesh/aeraki/issues/285
=> fix nil pointer

Makefile, cmd/aeraki/main.go, demo/common_func.sh, demo/gateway/demo-ingress.yaml, demo/install-aeraki.sh, demo/uninstall-aeraki.sh, demo/uninstall-demo.sh, docker/Dockerfile, k8s/aeraki.yaml, manifests/charts/aeraki/templates/deployment.yaml, manifests/charts/aeraki/values.yaml, pkg/bootstrap/options.go, pkg/bootstrap/server.go, pkg/config/constants/constants.go, pkg/controller/kube/namesapce.go, pkg/controller/kube/sidecar_bootstrap_config.go, test/e2e/metaprotocol/metaprotocol_test.go, test/e2e/metaprotocolgateway/metaprotocol_gateway_test.go, test/e2e/scripts/addons.sh, test/e2e/scripts/aeraki.sh, test/e2e/scripts/istio.sh, test/e2e/scripts/uninstall-addons.sh, test/e2e/scripts/uninstall-istio.sh, test/e2e/util/kube_utils.go
Support for aeraki to be installed in other namespaces
=> make aeraki address configurable

demo/uninstall-aeraki.sh, test/e2e/scripts/remove-aeraki-configmap.sh
=> remove aeraki configmap in namepace if we uninstall aeraki

plugin/metaprotocol/metaprotocolproxy.go
```
2023-04-19T08:25:22.213465Z	info	debounce stable[1] 5: 1.000447751s since last event, 1.000458261s since last debounce
2023-04-19T08:25:22.213561Z	info	envoyfilter-controller	found generator for port: tcp-metaprotocol-dubbo
zipkin:<address:"zipkin.istio-system:9411" > zipkin:<address:"zipkin.istio-system:9411" > 2023-04-19T08:25:22.215728Z	info	envoyfilter-controller	found generator for port: tcp-metaprotocol-dubbo
zipkin:<address:"zipkin.istio-system:9411" > zipkin:<address:"zipkin.istio-system:9411" > 2023-04-19T08:25:22.242532Z	info	envoyfilter-controller	deleting EnvoyFilter: namespace: istio-system name: aeraki-inbound-org.apache.dubbo.samples.basic.api.demoservice-20880 {"kind":"EnvoyFilter","apiVersion":"networking.istio.io/v1alpha3","metadata":{"name":"aeraki-inbound-org.apache …
```
=> use metaprotocol-generator generatorLog

cmd/aeraki/main.go, docker/Dockerfile, k8s/aeraki.yaml, manifests/charts/aeraki/templates/deployment.yaml, pkg/bootstrap/options.go, pkg/bootstrap/server.go, pkg/util/error.go
fixed https://github.com/aeraki-mesh/aeraki/issues/348
=> add aeraki health check

cmd/aeraki/main.go, k8s/aeraki.yaml, manifests/charts/aeraki/templates/deployment.yaml
fixed https://github.com/aeraki-mesh/aeraki/issues/353
=> fix bug for AERAKI_IS_MASTER env

.github/workflows/e2e-dubbo.yaml, .github/workflows/e2e-metaprotocol-gateway.yaml, .github/workflows/e2e-metaprotocol.yaml, .github/workflows/e2e-redis.yaml, .github/workflows/e2e-thrift.yaml, demo/install-demo.sh, demo/metaprotocol-brpc/brpc-sample.yaml, demo/metaprotocol-dubbo-app-level/dubbo-sample.yaml, demo/metaprotocol-dubbo/dubbo-sample.yaml, demo/metaprotocol-thrift/outlier-detection/outlier-detection.yaml, demo/metaprotocol-thrift/thrift-sample.yaml, test/e2e/metaprotocol/testdata/metaprotocol-sample.yaml, test/e2e/metaprotocolgateway/testdata/ingress-gateway.yaml, test/e2e/scripts/istio.sh, test/e2e/scripts/uninstall-istio.sh
=> upgrade aeraki to support istio 1.16.5

pkg/model/metaprotocol/application_protocol.go
remove sync.Mutex
* [ x ] Have you modified the related document?
=> replace map[string]string with sync.Map

internal/controller/istio/controller.go, internal/xds/cache_mgr.go, internal/xds/callbacks.go, internal/xds/server.go
=> fix aeraki memory leak when node info update

manifests/charts/aeraki/templates/clusterrole.yaml
The Helm chart currently does not have the correct permissions for webhooks. `k8s/aeraki.yaml` has them, so we're copying these over
https://github.com/aeraki-mesh/aeraki/blob/974bcbbf2bfbd888967559c7f45cbe9192fd9ba8/k8s/aeraki.yaml#L213C3-L218C12
=> fix: ClusterRole webhook permissions

go.mod, go.sum
fix: update lestrrat-go/jwx to v1.2.28 to fix CVE-2024-21664
=> fix: update lestrrat-go/jwx to v1.2.28 to fix CVE-2024-21664

demo/thrift/thrift-sample.yaml
The startup message for the multitool mentions that the docker repo has changed
> ## 05 Jan 2022 - Important note about name/org change:
> Few years ago, I created this tool with Henrik Høegh, as `praqma/network-multitool`. Praqma was bought by another company, and now the "Praqma" brand is being dismantled. This means the network-multitool's git and docker repositories must go. Since, I was the one maintaining the docker image for all these years, it was decided by the current representatives of the company to hand it over to me so I can continue maintaining it. So, apart from a small change in the repository name, nothing has changed. 
>The existing/old/previous container image `praqma/network-multitool` will continue to work and will remain available for **"some time"** - may be for a …
=> Update network-multitool docker address
